GalaxySports.WebUI/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GalaxySports.WebUI.Controllers
{
    public class AboutController : Controller
    {
        public ViewResult History()
        {
            return View();
        }

        public ViewResult Career()
        {
            return View();
        }

        public ViewResult ContactUs()
        {
            return View();
        }
    }
}

GalaxySports.WebUI/Controllers/CartController.cs
using GalaxySports.Domain.Abstract;
using GalaxySports.Domain.Entities;
using GalaxySports.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GalaxySports.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        private IUserRepository userRepository;
        private IOrderRepository orderRepository;
        private IOrderProductRepository orderProductRepository;

        public CartController(IProductRepository productRepository, IOrderProcessor processor, IUserRepository usrRepository, IOrderRepository ordRepository, IOrderProductRepository ordProductRepository)
        {
            repository = productRepository;
            orderProcessor = processor;
            userRepository = usrRepository;
            orderRepository = ordRepository;
            orderProductRepository = ordProductRepository;
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveSingleItemFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, -1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public ViewResult Summary(Cart cart)
        {
            return View(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
            ViewBag.TotalSum = cart.ComputeTotalValue();
            return View(GetShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(orderRepository, orderProductRepository, cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(GetShippingDetails());
            }
        }

        private ShippingDetails GetShippingDetails()
        {
            var shippingDetails = new ShippingDetails();
            if (User.Identity.IsAuthenticated)
            {
                //var user = userRepository.GetUserByLogin(User.Identity.Name);
                var user = userRepository.Users.FirstOrDefault(u => u.Login == User.Identity.Name);
                shippingDetails.UserId = user.UserID;
                shippingDetails.Name = string.Format("{0} {1}", user.Name, user.Surnaame);
                shippingDetails.PhoneNumber = user.PhoneNumber;
            }
            return shippingDetails;
        }
    }
}

GalaxySports.WebUI/Controllers/NavController.cs
using GalaxySports.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GalaxySports.Domain.Entities;

namespace GalaxySports.WebUI.Controllers
{
    public class NavController : Controller
    {
        private ICategoryRepository categoryRepository;

        public NavController(ICategoryRepository repository)
        {
            categoryRepository = repository;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = categoryRepository.Categories
                .Where(x => !x.Deleted)
                .Select(x => x.Name)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }

        public FileContentResult GetImage(int categoryId)
        {
            Category category = categoryRepository.Categories.FirstOrDefault(n => n.CategoryID == categoryId);
            if (category != null)
            {
                return File(category.ImageData, category.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

GalaxySports.WebUI/Views/Shared/CommentSummary.cshtml
@model GalaxySports.WebUI.Models.CommentViewModel
<div class="commentItem">
    <div>
        <h4>@Model.User.Name</h4>
    </div>
    <div class="commentDate">
        @Model.Time.Date.ToString("dd.MM.yyyy")
    </div>
    <div>
        @Model.CommentText
    </div>
</div>

GalaxySports.WebUI/Views/Shared/NewsSummary.cshtml
@model GalaxySports.Domain.Entities.News
@if (Model.ImageData != null)
{
    <div class="newsItem" style="min-height: 215px">
        <div>
            <h3>@Model.Title</h3>
        </div>
        <div class="mewsDate">
            @Model.PublishTime.ToString("dd.MM.yyyy")
        </div>
        <div style="float: left; margin-right: 20px">
            <img width="150" height="150" src="@Url.Action("GetImage", "Home", new { Model.NewsID })" />
            @*<img width="150" height="150" src="@Url.Content("~/Content/Images/galaxy_no_image.png")"/>*@
        </div>
        <div class="newsBody">
            @Model.Body
        </div>
    </div>
}
else
{
    <div class="newsItem">
        <div>
            <h3>@Model.Title</h3>
        </div>
        <div class="mewsDate">
            @Model.PublishTime.ToString("dd.MM.yyyy")
        </div>
        <div class="newsBody">
            @Model.Body
        </div>
    </div>
}

GalaxySports.WebUI/Views/Shared/OrderSummary.cshtml
@model GalaxySports.WebUI.Models.OrderViewModel
<div class="productItem">
    <table>
        <tr>
            <td colspan="2">
                <h3>Ship to</h3>
            </td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>@Model.Order.UserName</td>
        </tr>
        <tr>
            <td>Phone:</td>
            <td>@Model.Order.PhoneNumber</td>
        </tr>
        <tr>
            <td colspan="2">
                <h3>Address</h3>
            </td>
        </tr>
        <tr>
            <td>Country:</td>
            <td>@Model.Order.Country</td>
        </tr>
        <tr>
            <td>State:</td>
            <td>
                @Model.Order.State</td>
        </tr>
        <tr>
            <td>City:</td>
            <td>@Model.Order.City</td>
        </tr>
        <tr>
            <td>Address:</td>
            <td>@Model.Order.Address</td>
        </tr>
        <tr>
            <td colspan="2">
                <h3>Options</h3>
            </td>
        </tr>
        <tr>
            <td>
                @Model.Order.GiftWrap
            </td>
            <td>Gift wrap these items
            </td>
        </tr>
        <tr>
            <td>
                @Model.Order.RushOrder
            </td>
            <td>Rush order
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h3>Payment options</h3>
            </td>
        </tr>
        <tr>
            <td>Payment method:</td>
            <td>@Model.Order.PaymentMethod
            </td>
        </tr>
    </table>
    <h3>Products:</h3>
    <table width="90%" align="center">
        <thead>
            <tr>
                <th align="left">Item</th>
                <th align="right">Price</th>
                <th align="center">Quantity</th>
                <th align="right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.OrderProducts)
            {
                <tr>
                    <td align="left">@(Model.Products.FirstOrDefault(x => x.ProductID == product.ProductID).Name)</td>
                    <td align="right">@product.Price.ToString("c")</td>
                    <td align="center">@product.Quantity</td>
                    <td align="right">@((product.Quantity * product.Price).ToString("c"))</td>
                </tr>	  
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" align="right" style="font-weight: bold">Total:</td>
                <td align="right">@(Model.OrderProducts.Sum(x => x.Price * x.Quantity).ToString("c"))</td>
            </tr>
        </tfoot>
    </table>
    <h3>Order information</h3>
    <table>
        <tr>
            <td>Delivered:
            </td>
            <td>
                @Model.Order.Delivered
            </td>
            <td>
                @if (!Model.Order.Delivered)
                {
                    using (Html.BeginForm("DeliverOrder", "ServiceStaff"))
                    {
                    @Html.Hidden("OrderId", Model.Order.OrderID)
                    <input class="actionButtons" type="submit" value="Order is delivered" />
                    }
                }
            </td>
        </tr>
        <tr>
            <td>Paid:
            </td>
            <td>
                @Model.Order.Paid
            </td>
            <td>
                @if (!Model.Order.Paid)
                {
                    using (Html.BeginForm("PayOrder", "ServiceStaff"))
                    {
                    @Html.Hidden("OrderId", Model.Order.OrderID)
                    <input class="actionButtons" type="submit" value="Order is paid" />
                    }
                }
            </td>
        </tr>
        <tr>
            <td>Order Is Executed:
            </td>
            <td>
                @Model.Order.TheOrderIsExecuted
            </td>
            <td>
                @if (Model.Order.Delivered && Model.Order.Paid && !Model.Order.TheOrderIsExecuted)
                {
                    using (Html.BeginForm("ExecuteOrder", "ServiceStaff"))
                    {
                    @Html.Hidden("OrderId", Model.Order.OrderID)
                    <input class="actionButtons" type="submit" value="Order is executed" />
                    }
                }
            </td>
        </tr>
    </table>
</div>

GalaxySports.WebUI/Views/Shared/ProductSummary.cshtml
@model GalaxySports.Domain.Entities.Product

<div class="productItem">
    <table>
        <tr>
            <td style="vertical-align: top">
                <div style="float: left; margin-right: 20px">
                    @if (Model.ImageData != null)
                    {
                        <img width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
                    }
                    else
                    {
                        <img width="150" height="150" src="@Url.Content("~/Content/Images/galaxy_no_image.png")"/>
                    }
                </div>
            </td>
            <td style="vertical-align: top">
                <h3>@Html.ActionLink(Model.Name, "Product", "Product", new { ID = Model.ProductID }, null)</h3>
                @Model.Description
                <div style="margin-top: 30px">
                    @if (User.Identity.IsAuthenticated)
                    {
                        using (Html.BeginForm("AddToCart", "Cart"))
                        {
                        @Html.HiddenFor(x => x.ProductID)
                        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                        <input type="submit" value="+ Add to cart" />
                        }
                    }
                    else
                    {
                        <h4>
                            <div style="color: red">You must be logged in to be able to make purchases!</div>
                        </h4>
                    }
                    <h4>@Model.Price.ToString("c")</h4>
                </div>
            </td>
        </tr>
    </table>
</div>

GalaxySports.WebUI/Views/Shared/_AdminLayout.cshtml
@*<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("`/Content/Admin.css")" rel="stylesheet" type="text/css" />
    
    
    
    <script src="@Url.Content("`/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("`/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("`/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>



    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script src="../../Scripts/jquery.validate.min.js"></script>
    <script src="../../Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div> 
        }
        @RenderBody()
    </div>
</body>
</html>*@


<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="@Url.Content("~/Content/Images/GalaxySportsIcon.png")" />
    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script src="../../Scripts/jquery.slidertron-1.1.js"></script>
</head>

<body>
    <div id="wrapper">
        <div id="header-wrapper">
            <div id="header">
                <div id="logo">
                    <h1>@Html.ActionLink("Galaxy Sports", "Index", "Admin")</h1>
                    <p>Admin part</p>
                </div>
            </div>
        </div>
        <!-- end #header -->
        <div id="page">
            <div id="page-bgtop">
                <div id="page-bgbtm">
                    <div id="sidebar">
                        <ul>
                            <li>
                                @*<div id="search">
                                    <form method="get" action="#">
                                        <div>
                                            <input type="text" name="s" id="search-text" value="" />
                                            <input type="submit" id="search-submit" value="GO" />
                                            @using (Html.BeginForm("List", "Product"))
                                            {
                                                <input type="text" name="TextForSearch" id="search-text" />
                                                <input type="submit" id="search-submit" value="GO" />
                                            }
                                        </div>
                                    </form>
                                </div>*@
                                <div style="clear: both;">&nbsp;</div>
                            </li>
                            <li>
                                <h2>@Html.ActionLink("Home", "Index", "Home")</h2>
                            </li>
                            <li>
                                <h2>Orders</h2>
                                <ul>
                                    <li>@Html.ActionLink("News", "News", "Admin")</li>
                                    <li>@Html.ActionLink("Categories", "Categories", "Admin")</li>
                                    <li>@Html.ActionLink("Products", "Products", "Admin")</li>
                                    <li>@Html.ActionLink("Users", "Users", "Admin")</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- end #sidebar -->
                    <div id="content">
                        @RenderBody()
                        <div style="clear: both;">&nbsp;</div>
                    </div>
                    <!-- end #content -->
                    <div style="clear: both;">&nbsp;</div>
                </div>
            </div>
        </div>
        <!-- end #page -->
    </div>
    <div id="footer">
        <p>Copyright © 2013 RDT Software Solutions. All rights reserved.</p>
    </div>
    <!-- end #footer -->
</body>
</html>

GalaxySports.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="@Url.Content("~/Content/Images/GalaxySportsIcon.png")" />
    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script src="../../Scripts/jquery.slidertron-1.1.js"></script>
</head>

<body>
    <div id="wrapper">
        <div id="header-wrapper">
            <div id="header">
                <div id="logo">
                    <h1>@Html.ActionLink("Galaxy Sports", "Index", "Home")</h1>
                    <p>Healthy mind in healthy body</p>
                </div>
                @{Html.RenderAction("Summary", "Cart");}
            </div>
        </div>
        <!-- end #header -->
        <div id="page">
            <div id="page-bgtop">
                <div id="page-bgbtm">
                    <div id="sidebar">
                        <ul>
                            <li>
                                @*<div id="search">
                                    <form method="get" action="#">
                                        <div>
                                            <input type="text" name="s" id="search-text" value="" />
                                            <input type="submit" id="search-submit" value="GO" />
                                            @using (Html.BeginForm("List", "Product"))
                                            {
                                                <input type="text" name="TextForSearch" id="search-text" />
                                                <input type="submit" id="search-submit" value="GO" />
                                            }
                                        </div>
                                    </form>
                                </div>*@
                                <div style="clear: both;">&nbsp;</div>
                            </li>
                            <li>
                                <h2>@Html.ActionLink("Home", "Index", "Home")</h2>
                            </li>
                            <li>
                                <h2>Categories</h2>
                                @{Html.RenderAction("Menu", "Nav");}
                            </li>
                            <li>
                                <h2>@Html.ActionLink("Search", "Index", "Search")</h2>
                            </li>
                            <li>
                                <h2>@Html.ActionLink("Shops", "Index", "Shops")</h2>
                            </li>
                            <li>
                                <h2>About</h2>
                                <ul>
                                    <li>@Html.ActionLink("History", "History", "About")</li>
                                    <li>@Html.ActionLink("Career", "Career", "About")</li>
                                    <li>@Html.ActionLink("Contact Us", "ContactUs", "About")</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- end #sidebar -->
                    <div id="content">
                        @RenderBody()
                        <div style="clear: both;">&nbsp;</div>
                    </div>
                    <!-- end #content -->
                    <div style="clear: both;">&nbsp;</div>
                </div>
            </div>
        </div>
        <!-- end #page -->
    </div>
    <div id="footer">
        <p>Copyright © 2013 RDT Software Solutions. All rights reserved.</p>
    </div>
    <!-- end #footer -->
</body>
</html>

GalaxySports.WebUI/Views/Shared/_ServiceStaffLayout.cshtml
@*@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>_ServiceStaffLayout</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>*@

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="@Url.Content("~/Content/Images/GalaxySportsIcon.png")" />
    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script src="../../Scripts/jquery.slidertron-1.1.js"></script>
</head>

<body>
    <div id="wrapper">
        <div id="header-wrapper">
            <div id="header">
                <div id="logo">
                    <h1>@Html.ActionLink("Galaxy Sports", "Index", "ServiceStaff")</h1>
                    <p>Service Staff part</p>
                </div>
            </div>
        </div>
        <!-- end #header -->
        <div id="page">
            <div id="page-bgtop">
                <div id="page-bgbtm">
                    <div id="sidebar">
                        <ul>
                            <li>
                                @*<div id="search">
                                    <form method="get" action="#">
                                        <div>
                                            <input type="text" name="s" id="search-text" value="" />
                                            <input type="submit" id="search-submit" value="GO" />
                                            @using (Html.BeginForm("List", "Product"))
                                            {
                                                <input type="text" name="TextForSearch" id="search-text" />
                                                <input type="submit" id="search-submit" value="GO" />
                                            }
                                        </div>
                                    </form>
                                </div>*@
                                <div style="clear: both;">&nbsp;</div>
                            </li>
                            <li>
                                <h2>@Html.ActionLink("Home", "Index", "Home")</h2>
                            </li>
                            <li>
                                <h2>Orders</h2>
                                <ul>
                                    <li>@Html.ActionLink("All orders", "Index", "ServiceStaff")</li>
                                    <li>@Html.ActionLink("My queue", "MyQueue", "ServiceStaff")</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <!-- end #sidebar -->
                    <div id="content">
                        @RenderBody()
                        <div style="clear: both;">&nbsp;</div>
                    </div>
                    <!-- end #content -->
                    <div style="clear: both;">&nbsp;</div>
                </div>
            </div>
        </div>
        <!-- end #page -->
    </div>
    <div id="footer">
        <p>Copyright © 2013 RDT Software Solutions. All rights reserved.</p>
    </div>
    <!-- end #footer -->
</body>
</html>